sudo: true
language: node_js
node_js:
  - '4.0'
install: npm install
before_script:
  - chmod +x ./update-stations.sh
  - chomd +x ./make-station-history.sh
  - npm run battuta
  - npm run lint-stations
script:
  - "./make-station-history.sh"
  - npm run battuta
after_success: npm run lint-stations
deploy:
  - provider: script
    skip_cleanup: true
    script: "./update-stations.sh"
    on:
      branch: master



