sudo: true
language: node_js
node_js:
- '5.0'
install: npm install
before_script:
- chmod +x ./make-station-history.sh
- npm run battuta
- npm run lint-stations
script:
- "./make-station-history.sh"
- npm run battuta
after_success: npm run lint-stations
deploy:
- provider: s3
  access_key_id: ${ACCESS_KEY_ID}
  secret_access_key:
    secure: "FycMIpaOzWq+yEL0e2FaA1bqLfTszTKI+ERuKdfJRBhNNolc6qeEiHVWcyVtfXmAkSzTfiVCe1Mqa+pIWWpddj6iCv1BE8BI2SzCbvuFCtl33XG6V0xBdcR8Jvo2ziMewe+/LW5UResnYSsTq7PZVFAM4W/Umtn//cmOxUwZEjoeUNHEJdw4HcP2tsk1vmV7mZVD5yLGvyIZGMkUM9nCBywN1zKNqU9DPsw6c3ZxTPaJtxpuM5WBUBC0+HNQuJPcrkP8v+jsi937I1OWirK7B2i6Cpled/on5gmm9oKyTl7GRVTbsYoi1pz0cZeWRN/c4gwoMb13OPsTecVuiR+9Q+3kCEmjCcuD4B3N8QQ1m5wWJs6mSp2d61LtDIL76hyv/yUDS/NJGWZx4lZ5HAjAFE0e61CyGSgvIDAya7uRv9dgN8A4ie99C+aZRPVAaNY10CGkDFUqrMgn7ApG6d95sRw6Y5hexBP0FJ0eHnvyBTu9OhKM2G7ktSh4d73DuuevxtH++S8uXY3lA3b8+1l4wbuZgW7kLUpxOUV5kWpGAXS6qtXeba6r62mPx4hvwiLv4rsdza2W455l4t4deql16N1eCTbd6uySveoXxH7Qs7lGv6f1sviYHuEGb0yd6NeeTIg1kjnnFmHBrR2NeO6joDP4cGdAnNV+FbV5/9HvmyQ="
  bucket: battuta
  skip_cleanup: true
  local_dir: data
  acl: public_read
  on:
    branch: feature/nightly-build
